### ISSUE TITLE
I am here to answer your questions.

### ISSUE THREAD

**Issue by wentaozhu** [wentaozhu/Hierarchical-ELM-Network#1]

**Comment by juneying** [comment]
Hi,

Good Day. 
Thank for sharing the code of Hierarchical-ELM-Network in the GitHub.

I have downloaded the code of Hierarchical-ELM-Network and want to try it by running the code from the demo.m. However, the demo code stop working when the Net_train function is called. In the Net_train function, the problem occurs when it call the Net_FilterBank function. This is due to the missing of parameter named as Net.SigPara which is required in the Net_FilterBank function when it is called in the Net_train function.  

May I know what is the value used for the Net.SigPara?
Also, there is missing a folder named as "common" where the patch is added in the demo.m.

Thanks 

Best Regards,
June

**Comment by wentaozhu** [comment]
Dear June,

Thank you very much for your interest. I think you refer to alpha_1, alpha_2 in the paper http://www.jdl.ac.cn/doc/2011/2015724847265241_ijcnn2015-cameraready.pdf

The values for different datasets are shown in Table 2.

I think common is used for if your matlab is missing some functions, you can copy that system function into the folder. I remember it is so at that time, if I am not wrong. Just tell me, if it does not work.

Feel free to discuss any questions!

Thanks,
Wentao

**Comment by juneying** [comment]
Hi Wentao,

After the value of alpha_1 and alpha_2 are inserted into the code, the program now works perfectly !
Yes, you are right, I already ignore the code that add the path for common folder, this does not affect the running of the program.

Thank you very much !

Best Regards,
June

**Comment by wentaozhu** [comment]
Dear June,

Glad to hear that! Good luck!

Wentao
